# Generated by Django 2.2.6 on 2019-11-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=60)),
                ('nachname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
